use_frameworks!
#use_modular_headers!
inhibit_all_warnings!

platform :ios, '11.0'

target 'GofMediatorOCDemo_Example' do
  pod 'GofMediatorCategory', '0.1.0'
  pod 'GofMediatorExtension', '0.1.0'
  pod 'GofAModule', '0.2.0'
  pod 'GofBModule', '0.1.0'
  pod 'GofMediator', '0.2.0'

  target 'GofMediatorOCDemo_Tests' do
    inherit! :search_paths

    
  end
end
